name: flash
channels:
  - defaults
dependencies:
  - python=3.10.14
  - pip=24.0
  - numpy=1.26.4
  - pillow=10.3.0
  - pytesseract=0.3.10
  - pyyaml=6.0.1
  - regex=2024.5.15
  - requests=2.32.3
  - sympy=1.12.1
  - torch=2.3.0
  - transformers=4.41.2
  - tqdm=4.66.4
  - pip:
      - certifi==2024.6.2
      - charset-normalizer==3.3.2
      - colorama==0.4.6
      - fsspec==2024.5.0
      - huggingface-hub==0.23.2
      - idna==3.7
      - jinja2==3.1.4
      - markupsafe==2.1.5
      - networkx==3.3
      - packaging==24.0
      - safetensors==0.4.3
      - sentencepiece==0.2.0
      - tokenizers==0.19.1
      - typing-extensions==4.12.1
      - urllib3==2.2.1
